spring:
  profiles:
    active:
      - dog
      - EN
      - dev

guru:
  username: YmlUser
  password: YmlPassword
  jdbcUrl: YmlUrl

---
spring:
  profiles: prod

guru:
  username: YmlProdUser
  password: YmlProdPassword
  jdbcUrl: YmlProdUrl